apiVersion: v1
kind: Service
metadata:
  name: votion-service
  labels:
    name: votion-serivce
    app: demo-votion-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: votion-app-pod
    app: demo-votion-app
